version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: mysql-linkedin-clone
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=linkedin_clone
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/opt/mysql/data
    expose:
      - 3306

  app:
    container_name: api-linkedin-clone
    build: .
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
